backend:
  name: git-gateway
  branch: master

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "battlemaps"
    label: "Battlemaps"
    folder: "battlemap"
    create: true
    slug: "{{fields.author}}-{{fields.title}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Artist (patreon slug preferred)", name: "artist", widget: "string"}
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Reddit Post URL", name: "postUrl", widget: "string"}
      - {label: "Reddit Comment URL (Description)", name: "descUrl", widget: "string"}
      - {label: "Credit", name: "credit", widget: "markdown"}
      - {label: "Variants Info", name: "body", widget: "markdown"}
